### ISSUE TITLE
Error in typescript converting utm to latlng

### ISSUE THREAD

**Issue by DennysXor** [shahid28/utm-latlng#10]
var M is not being properly declared in Line 126 of UTMLatLng.js file
it is
M = y / 0.9996;
should be
var M = y / 0.9996;

**Comment by shahid28** [comment]
Issue fixed

**Comment by larsmars** [comment]
Is it posible to do a new npm release with this fix?
The latest version on npm is 2 years old (1.0.5)
https://www.npmjs.com/package/utm-latlng

I am getting this error when using the npm package.
`ReferenceError: M is not defined`

**Comment by shahid28** [comment]
Thanks, @larsmars  for notifying, this is done
