### ISSUE TITLE
Problem with UTM Zone 32

### ISSUE THREAD

**Issue by mikelortega** [shahid28/utm-latlng#12]
I cannot see why there is a first condition for the zone 32.
```
    if (LongTemp >= 8 && LongTemp <= 13 && latitude > 54.5 && latitude < 58) {
        ZoneNumber = 32;
```
With this code, the coordinate lat:55.0 long:12.5 returns zone 32, while other programs and converters return zone 33.
The zone exceptions are [mentioned here](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Exceptions) and I cannot find anything about that condition.

**Comment by peterkimga** [comment]
Hi

I got the same issue with this class now. Will this be fixed?
