### ISSUE TITLE
ReferenceError: ZoneNumber is not defined

### ISSUE THREAD

**Issue by srothst1** [shahid28/utm-latlng#22]
Hello :wave: 

I have been using the `utm-latlng` for a few months now and I am overall very impressed by the API. However, I have recently come across an issue and I am not sure how to proceed.

When I call the function `convertLatLngToUtm`,
```
const geomPoint = featureGeom as GeoJSON.Point;
var utmCrd = this.utm.convertLatLngToUtm(geomPoint.coordinates[1], geomPoint.coordinates[0], 10);
```
I receive the following error:
```
ReferenceError: ZoneNumber is not defined
```
I am confused because `convertLatLngToUtm` does not appear to have `ZoneNumber` as a parameter. Please note that I am using `"utm-latlng": "^1.0.6"`. Any suggestions would be welcomed.

**Comment by shahid28** [comment]
Hi, please try with "utm-latlng": "^1.0.7" version

**Comment by shahid28** [comment]
Please let me know if you are facing any issues.

**Comment by srothst1** [comment]
Hi @shahid28. Thank you for your timely response. Upgrading to `"utm-latlng": "^1.0.7"` has resolved my error.

**Comment by srothst1** [comment]
Hi @shahid28. I am sorry for this update - but `"utm-latlng": "^1.0.7"` has not actually resolved my error. Is there any more information that I can provide you to help reach a solution?

The confusion regarding whether this was fixed on not stems from an npm issue that I am having in my repository.

**Comment by shahid28** [comment]
Hi @srothst1, please provide the sample data and code in which error is occur. So I can reporoduce the error on my side.

**Comment by giraphics** [comment]
Hi @shahid28 the above reported issue is fixed with the es6 version of utm-latlng.

**Comment by shahid28** [comment]
Hi @giraphics, thanks for notifying me, @srothst1  please try with the es6 version of UTM-latlng.
