### ISSUE TITLE
Round values?

### ISSUE THREAD

**Issue by juliocbcotta** [shahid28/utm-latlng#3]
It looks like the lib is rounding the results.
In some online converters from lat/lng to UTM I got :
lat: -23.5980369
lng: -46.6808732

E = 328492.93
N = 7389267.92
Zone = 23k

but with this lib

E = 328493
N = 7389268
Zone = 23k

Would it be possible to not to round the result?

**Comment by shahid28** [comment]
Please checkout the lets code or update the node module
