### ISSUE TITLE
Found a bug?

### ISSUE THREAD

**Issue by juliocbcotta** [shahid28/utm-latlng#4]
It looks like here
```
if ('N' === ZoneLetter) {
        NorthernHemisphere = 1;
    } else {
        NorthernHemisphere = 0;
        this.y -= 10000000.0;
    }
```
the `this.y` does not exist and the calculation fails to happen in a right way. Could you check?
I removed the `this.` and It looks like it worked.

**Comment by juliocbcotta** [comment]
@shahid28 
I think I can confirm the bug.
If you convert
lat: -23.5980369
lng: -46.6808732

to UTM:
E = 328492.93
N = 7389267.92
Zone = 23k

and back to lat/lng it will not be any close of the original lat/lng.
Making the change proposal above solves it.

**Comment by shahid28** [comment]
Thanks @BugsBunnyBR for notifying this issue, I fix this issue as you mention above solution. Please verify this issue is fixed or not after that is will close this issue in git.
Thaks again.

**Comment by juliocbcotta** [comment]
Thanks, it worked.
