### ISSUE TITLE
Passing zone in "utm.convertUtmToLatLng"

### ISSUE THREAD

**Issue by DanielIbaseta** [shahid28/utm-latlng#5]
When passing a zone in the function convertUtmToLatLng it soesn't know if it's North hemisphere or south hemisphere. I will provide an example. If I am i coordinates (lat: 43.5216 lng:-5.6101) the conversion to UTM returns:
`
{ Easting: 289054.868,
  Northing: 4822059.711,
  ZoneNumber: 30,
  ZoneLetter: 'T' }
`

But if I make the conversion back with the function:
`
utm.convertUtmToLatLng(289054.868, 4822059.711, 30, 'T')
`

It gives the incorrect result:
`{ lat: -46.72170894733108, lng: -5.760423230528069 }`

I can only get a correct answer when i pass an "N" in the Zone parameter of "convertUtmToLatLng" function. It would be nice if this function distinguishes between zone letters that are in the North or in the South hemisphere. I think that the solution is checking the zone letter and if it is between N to Z for the North hemisphere and A to M for the south. I made the change myself in the file "UTMLatLng.js", I let it right here:

> if (['N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'].indexOf(ZoneLetter) > -1) {
    NorthernHemisphere = 1;
} 
else {
    NorthernHemisphere = 0;
    y -= 10000000.0;
}

**Comment by ajcasanova** [comment]
Today, 15 Jun 2019 still having this issue with node package version. 
This fix is newer than the code avaliable via npm. Please, update there. Thank you!!
