### ISSUE TITLE
Como utilizarla

### ISSUE THREAD

**Issue by 3jFernando** [shahid28/utm-latlng#6]
Hola, oye necesito implementar esto en mi app Ionic 3 con mapas y quiero convertir las coordenadas LatLng a UTM. ¿Se puede aplicar esto a Ionic 3 y Angular 6?

Ademas,  en este metodo: utm.convertLatLngToUtm(latitude, longitude,precision); 
¿que es la precision?

Gracias.

**Comment by shahid28** [comment]
Hi, Sorry for so late reply,
precision is the number of digit after the decimal point.
