### ISSUE TITLE
License

### ISSUE THREAD

**Issue by donmccurdy** [shahid28/utm-latlng#8]
Please consider adding a `LICENSE` file to the repository, and referencing it in the `package.json` file. Without a license, it is ambiguous whether and how others are allowed to use this code.

- https://help.github.com/en/articles/licensing-a-repository
- https://docs.npmjs.com/files/package.json#license

Thanks!

**Comment by shahid28** [comment]
Thanks for the suggestion, LICENSE file and reference it adds to package.json.

**Comment by donmccurdy** [comment]
Thank you! 🙂
